package scripts

var Init = `
CREATE TABLE IF NOT EXISTS USER (
  ID char(32) COLLATE utf8_bin NOT NULL,
  USERNAME varchar(50) COLLATE utf8_bin NOT NULL,
  EMAIL varchar(50) CHARACTER SET utf8 NOT NULL,
  PASSWORD varchar(255) CHARACTER SET utf8 NOT NULL,
  USER_FLAG varchar(50) COLLATE utf8_bin NOT NULL,
  USER_FLAG_CODE varchar(50) COLLATE utf8_bin NOT NULL,
  MODE varchar(50) COLLATE utf8_bin NOT NULL,
  CREATED_TIME varchar(50) COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY USERNAME_UNIQUE (USERNAME),
  UNIQUE KEY EMAIL_UNIQUE (EMAIL),
  KEY idx_USER_CREATED_TIME (CREATED_TIME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE USER_SESSION (
	ID char(32) COLLATE utf8_bin NOT NULL,
	USER_ID char(32) COLLATE utf8_bin NOT NULL COMMENT ' ',
	USERNAME varchar(50) COLLATE utf8_bin NOT NULL,
	EMAIL varchar(50) COLLATE utf8_bin NOT NULL,
	LOGIN_TIME datetime NOT NULL,
	LAST_SEEN_TIME datetime NOT NULL COMMENT ' ',
	LOGIN_IP varchar(50) COLLATE utf8_bin NOT NULL,
	LAST_SEEN_IP varchar(50) COLLATE utf8_bin NOT NULL,
	SESSION_FLAGS longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(SESSION_FLAGS)),
	PRIMARY KEY (ID),
	KEY idx_USER_SESSION_USERNAME (USERNAME),
	KEY idx_USER_SESSION_EMAIL (EMAIL),
	KEY idx_USER_SESSION_LOGIN_TIME (LOGIN_TIME),
	KEY idx_USER_SESSION_LOGIN_IP (LOGIN_IP),
	KEY idx_USER_SESSION_LAST_SEEN_TIME (LAST_SEEN_TIME),
	KEY idx_USER_SESSION_LAST_SEEN_IP (LAST_SEEN_IP)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;`
