package scripts

var VerifyUser = `
UPDATE USER, USER_SESSION SET 
USER.USER_FLAG='',
USER.USER_FLAG_CODE=''
WHERE USER.ID=USER_SESSION.USER_ID
AND USER_SESSION.ID='__session_id'
AND USER.USER_FLAG='signup'
AND USER.USER_FLAG_CODE=?;`
